plugins {
    id "com.android.application"
}

android {
    namespace "au.com.classifire.admissionsigner"
    compileSdk 36

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    defaultConfig {
        applicationId "au.com.classifire.admissionsigner"
        minSdk 30
        targetSdk 36
        versionCode 3
        versionName "0.2.1-local"
    }
}

dependencies {
    testImplementation "junit:junit:4.13.2"
}
